set -g set-clipboard on
set -s escape-time 100 #Bugfix: Slow Background Query https://zenn.dev/saitogo/articles/22bb1c5b8c7e70?locale=en
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @resurrect-processes 'btop "bash run-sandbox.sh"'
run '~/.tmux/plugins/tpm/tpm'

